id: db34c333-7b4a-4bb8-8fbf-becce43bfa44
name: slack
description:  |
  ## What is Slack?

  Slack is a proprietary real-time business communication platform developed by an American software company Slack Technologies.

  ### Get started!

  Check out our Slack documentation to set up a notification channel and provide fast and consistent ways for the right personnel to be notified about incidents

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/notification-channels-control-where-send-alerts) to learn more about New Relic alerting for Slack. 
  
summary: |
  Send your New Relic alerts to Slack
icon: icon.svg
logo: logo.svg
level: New Relic
authors:
  - New Relic
title: Slack
documentation:
  - name: Slack installation docs
    description: |
      Send your New Relic alerts to Slack
    url: >-
      https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/notification-channels-control-where-send-alerts
