id: 8a7a7220-e8ec-4959-b35d-0fe082be8039
name: lacework
description: Integrate Lacework security data seamlessly into your observability experience.
summary: The following quickstart will contain three dashboards that surface different components of your security posture. 
icon: icon.svg
logo: logo.svg
level: Community
authors:
  - Lacework, Inc
title: Lacework Security Overview
documentation:
  - name: Lacework installation docs
    description: The only prerequisite is to setup the New Relic integration within the Lacework UI.  Details on how to do that can be found below!
    url: https://support.lacework.com/hc/en-us/articles/360005842354-New-Relic
keywords:
  - security,compliance
